import type { Metadata } from "next";
import { Poppins, Kanit } from "next/font/google";
import { AppProvider } from "@/provider";
import { cn } from "@nextui-org/theme";

import "./globals.css";
import { getVersion } from "@/lib";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "800"],
});
const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["marketplace"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" web-version={getVersion()}>
      <body className={cn(poppins.className, kanit.className)}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
